[http]
  [http.middlewares]

    [http.middlewares.api-stripprefix.stripPrefix]
      prefixes = ["/api/v1"]

  [http.routers]

    [http.routers.app-http]
      entryPoints = ["http"]
      service = "app"
      rule = "PathPrefix(`/api/v1`)"
      middlewares = ["api-stripprefix"]

  [http.services]

    [http.services.app]
     [[http.services.app.weighted.services]]
          name = "appv1"
          weight=1
             [[http.services.app.weighted.services]]
          name = "appv2"
          weight=3
             [[http.services.app.weighted.services]]
          name = "appv3"
          weight=2
          
    
      [http.services.appv1]
      [http.services.appv1.loadBalancer]
      
        [[http.services.appv1.loadBalancer.servers]]
          url = "http://127.0.0.1:5000"
          
            [http.services.appv2]
      [http.services.appv2.loadBalancer]
      
        [[http.services.appv2.loadBalancer.servers]]
          url = "http://127.0.0.1:5001"
          
            [http.services.appv3]
      [http.services.appv3.loadBalancer]
      
        [[http.services.appv3.loadBalancer.servers]]
          url = "http://127.0.0.1:5002"
          

